plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
   - 'cache/**/*'

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
