# frozen_string_literal: true

module Delaware
  class Generators
    # Generates markdown pages for profile intros.
    class ProfileIntro
      class << self
        def generate(profile, profiles, working_dir, base_output_dir)
          new(profile, profiles, working_dir, base_output_dir).generate
        end
      end

      attr_accessor :profile, :profiles, :working_dir, :base_output_dir

      def initialize(profile, profiles, working_dir, base_output_dir)
        self.profile = profile
        self.profiles = profiles
        self.working_dir = working_dir
        self.base_output_dir = base_output_dir
      end

      def template
        @template ||= File.read(File.join(__dir__, 'templates', 'profile_intro.md.erb'))
      end

      def start_tag
        '<!-- START AUTOGENERATED KEY ELEMENTS -->'
      end

      def end_tag
        '<!-- END AUTOGENERATED KEY ELEMENTS -->'
      end

      def output
        intro = File.read(output_file_name)
        key_elements = ERB.new(template, trim_mode: '-').result(binding)

        pattern = /#{Regexp.escape(start_tag)}.*?#{Regexp.escape(end_tag)}/m

        replacement = "#{start_tag}\n#{key_elements}#{end_tag}"

        @output ||= intro.gsub(pattern, replacement)
      end

      def base_output_file_name
        "StructureDefinition-#{profile.id}-intro.md"
      end

      def tag
        Config.tag
      end

      def tags
        # must_have_elements = profile.must_have_elements(profiles, working_dir)
        key_elements = profile.key_elements(profiles, working_dir)
        tag_elements = profile.tagged_elements(Config.tag_id)

        pc_path = Delaware::Helpers::FhirResourceDetails.primary_code_path(profiles, profile.type)

        {
          title: profile.title,
          link: "StructureDefinition-#{profile.id}.html",
          pc_path: pc_path,
          # NOTE: suppressing this for IG v1
          must_have_elements: [], # format_elements(must_have_elements),
          key_elements: format_elements(key_elements),
          tag_elements: format_elements(tag_elements)
        }
      end

      def output_file_directory
        File.join(base_output_dir)
      end

      def output_file_name
        File.join(output_file_directory, base_output_file_name)
      end

      def generate
        FileUtils.mkdir_p(output_file_directory)
        File.write(output_file_name, output)
      end

      private

      def format_elements(elements)
        elements.map do |element|
          target = element.id.split('.').drop(1).join('.')
          next if target.blank?

          {
            target: target,
            short: element.short&.gsub('|', '\|')
          }
        end
        .compact
        .uniq
      end
    end
  end
end
